<?php
require_once 'db.php'; 
include("auth.php");
if($_SERVER['REQUEST_METHOD'] == 'POST')
{
// print_r($_POST);
//       exit;

if($_POST["part"]=="")
{
  echo "Enter correct particulars";
}
else{
$part = $_POST["part"];
}
if($_POST["descript"]=="")
{
  echo "Enter correct decriptions";
}
else{
$desc = $_POST["descript"];
}

if($_POST["hq"]=="")
{
  echo "Enter correct Hours/Qty";
}
else{
$hq = $_POST["hq"];
}
if($_POST["unit"]=="")
{
  echo "Enter correct unit";
}
else{
$unit = $_POST["unit"];
}
if($_POST["amt"]=="")
{
  echo "Enter correct amt";
}
else{
$amt = $_POST["amt"];
}
if($_POST["head"]==" ")
{
  echo "Enter manager name";
}
else{
$manager = $_POST["head"];
echo "Manager Name: ".$manager; 
}
// $manager ="Soham";
$ru_id=$_SESSION['id'];

$m="pending";
$sql = "INSERT INTO requests (ru_id, manager, particulars, description, hq, unit, amt, m_status, f_status) VALUES ('$ru_id', '$manager', '$part', '$desc', '$hq', '$unit', '$amt', '$m', '$m')";
    if($con->query($sql)=== TRUE){
        echo "<p>New Record Successfully Created</p>";
    } else {
        echo "Error " . $sql . ' ' . $con->connect_error;
    }

  $query2="SELECT email FROM users where head='yes' and username='$manager' ";
  $result= $con->query($query2);
  // $result = mysqli_query($con,$query2);
    $rows = mysqli_num_rows($result);
    print_r($rows);
    $temp=mysqli_fetch_array($result);
  print_r($temp);
  // exit;
   $con->close();
  $email=$temp['email'];
  print_r($email);
  // exit;

if(isset($_POST['submit'])){

require 'vendor/PHPMailer/PHPMailer/src/PHPMailer.php';
require 'vendor/PHPMailer/PHPMailer/src/SMTP.php';
require 'vendor/autoload.php';
// require 'credentials.php';

$mail = new PHPMailer\PHPMailer\PHPMailer(true);                              // Passing `true` enables exceptions
try {
    //Server settings
    $mail->SMTPDebug = 2;                                 // Enable verbose debug output
    $mail->isSMTP();                                      // Set mailer to use SMTP
    $mail->Host = 'smtp.gmail.com';  // Specify main and backup SMTP servers
    $mail->SMTPAuth = true;                               // Enable SMTP authentication
    $mail->Username = 'shraddha1295@gmail.com';                 // SMTP username
    $mail->Password = 'shr@ddh@12';                           // SMTP password
    $mail->SMTPSecure = 'tls';                            // Enable TLS encryption, `ssl` also accepted
    $mail->Port = 587;                                    // TCP port to connect to

    //Recipients
    $mail->setFrom($_SESSION['email'], $_SESSION['username']);
    $mail->addAddress($email);     // Add a recipient
    // $mail->addAddress('ellen@example.com');               // Name is optional
    $mail->addReplyTo($_SESSION['email'], 'Information');
    // $mail->addCC('cc@example.com');
    // $mail->addBCC('bcc@example.com');

    //Attachments
    // $mail->addAttachment('/var/tmp/file.tar.gz');         // Add attachments
    // $mail->addAttachment('/tmp/image.jpg', 'new.jpg');    // Optional name

    //Content
    $mail->isHTML(true);                                  // Set email format to HTML
    $mail->Subject = 'Request for Freelancer';
    $mail->Body    = 'A new request has been generated by '.$_SESSION['username'];  
    $mail->AltBody = '';

    $mail->send();
    echo 'Message has been sent';
    // header("Location: login.php");
} catch (Exception $e) {
    echo 'Message could not be sent. Mailer Error: ';
}

}
}

 ?>
